version: '3'
services:
  node-app:
    container_name: express-node-app-container
    build: .
    # build: 
    #   context: .
    #   args:
    #     - NODE_ENV=production
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    # env_file:
    #   - ./.env
    environment:
      - PORT=4000
      - NODE_ENV=development
